### ISSUE TITLE
[1.18.2] Serene Seasons Console Spam

### ISSUE THREAD

**Issue by Aarods** [CCr4ft3r/DimensionalThreading-Reforged#10]
Minecraft Version
1.18.2

Mod Version
1.2.8

Notes
Starting the server with serene seasons leaves a massive spam of, "Season time skipped by 2" in the console.

Latest Log
[latest.log](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/files/12231179/latest.log)

Image
![image](https://github.com/CCr4ft3r/DimensionalThreading-Reforged/assets/110215990/ca5d7a5d-1df2-4fbd-9ba5-b5211ac2ca65)

**Comment by SrRapero720** [comment]
already reported to SereneSeasons (no answers yet)
https://github.com/Glitchfiend/SereneSeasons/issues/423

**Comment by CCr4ft3r** [comment]
Resolved in Serene Seaons
