### ISSUE TITLE
Modded bow can't shoot arrows.

### ISSUE THREAD

**Issue by rtxyd** [CCr4ft3r/DimensionalThreading-Reforged#3]
version: MC 1.19.2
mod: Dimensional-Threading-Reforged-1.19.2-1.2.7
Delete this mod then it's normal again. Vanilla bow works fine.

**Comment by CCr4ft3r** [comment]
Which bow mod are you using?

**Comment by rtxyd** [comment]
twilight forest, botania

**Comment by CCr4ft3r** [comment]
Thx. I will look into it

**Comment by CCr4ft3r** [comment]
I just tested it (ice and seeker bow) and these were just worked fine. Please try again with only these three mods installed.

**Comment by rtxyd** [comment]
OK, sorry for bothering you, it happens in a modpack, so I will close this issue until I find what mod cause the problem. But I am playing another pack, I'd wish somebody else finish this.
