### ISSUE TITLE
1.19.2 - When placed on Minecolonies based server all players cannot claim colonies.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CCr4ft3r/DimensionalThreading-Reforged#4]
Dimensional-Threading-Reforged-1.19.2-1.2.7.jar

Absolutely nothing should affect this but this mod somehow completely disrupted my mine colonies.

Test Environment https://www.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon

**Comment by P3rf3ctXZer0** [comment]
So I have no way to actually do that for you. I only know if your mod is present in my pack Minecolonies outright fails. Both Debug and Logs were clean. Which really shocked me. If you don't have time to figure out what you might be triggering the simple way to fix it is add a debug for your mod. Other than that I truly have no info for you.

**Comment by CCr4ft3r** [comment]
At least I would need the steps to reproduce the issue. How can I claim a colony with mine colonies?
