### ISSUE TITLE
Refined storage does not work

### ISSUE THREAD

**Issue by Sorro123** [CCr4ft3r/DimensionalThreading-Reforged#5]
Cannot use refined storage blocks

**Comment by CCr4ft3r** [comment]
Please provide the following information
- expected behaviour and actual one
- steps to reproduce it
- have any errors been logged?

**Comment by Sorro123** [comment]
Expected behavior: Items and blocks can be used normally and blocks update properly. Items can be inserted and extracted properly.

Steps to reproduce: Install RefinedStorage along with your mod. As far as I can tell, no other steps are needed.

No errors or anything else logged.

**Comment by Sorro123** [comment]
Once you test it you will probably see the issue, as items cannot be inserted or extracted from the storage system, and the blocks don't update properly.

**Comment by CCr4ft3r** [comment]
Please provide the steps to reproduce it. I'm not familiar with Refined Storage. I can insert items into the Storage Block with and without installed Dimensional Threadings. So please describe which blocks to place, which items to insert and what should happen with Dimensional Threading and what happened without it.

**Comment by CCr4ft3r** [comment]
closed due lack of information
